# Generated by Django 4.1.7 on 2023-03-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spotify", "0002_vote"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="score",
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
